version: '3.8'

services:
  php:
    build: ./php
    container_name: luz_dos_bichos
    ports:
      - "4040:80"
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - db
    environment: #criando as variaveis de ambiente
      - DB_HOST=db
      - DB_NAME=luz_bichos
      - DB_USER=luz_bichos_user
      - DB_PASS=luz_bichos_pass

  db:
    image: mysql:8.0
    container_name: luz_dos_bichos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luz_bichos
      MYSQL_USER: luz_bichos_user
      MYSQL_PASSWORD: luz_bichos_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  adminer: #criando o adminer para visualização das tabelas criadas
    image: adminer
    container_name: luz_dos_bichos_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: